name: deploy

on:
  push:
    branches: [ src ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
        with:
          submodules: recursive

      - uses: actions/checkout@v2
        with:
          ref: master
          path: public

      - uses: cachix/install-nix-action@v12
        with:
          nix_path: nixpkgs=channel:nixos-unstable

      - name: build
        run: nix-shell --run 'emacs -q --batch --load build.el'

      - name: setup git
        run: |
          git config user.name github-actions
          git config user.email github-actions@github.com

      - name: deploy github pages
        run: nix-shell --run 'emacs -q --batch --load deploy.el'

      - name: install SSH key
        uses: shimataro/ssh-key-action@v2
        with:
          name: id_ed25519
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          known_hosts: ${{ secrets.KNOWN_HOSTS }}

      - name: deploy to guix.org.cn
        run: nix-shell --run 'rsync -rhP --delete public/* github@guix.org.cn:/srv/www/guix.org.cn'
